image:
  repository: c63eqfuv.c1.gra9.container-registry.ovh.net/gfts/webapp
  pullPolicy: Always
  tag: "sha-ea9569e"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

certManager:
  enabled: true
  namespace: webapp
  installCRDs: true
  prometheus.enabled: false

service:
  type: ClusterIP
  port: 80
  targetPort: 9000

oauth2Proxy:
  enabled: true

global:
  redis:
    password: "${OAUTH2_PROXY_REDIS_SECRET}"

oauth2-proxy:
  namespaceOverride: webapp
  ingress:
    enabled: true
    className: webapp-nginx
    pathType: Prefix
    path: /oauth2
    hosts:
      - gfts.developmentseed.org
  config:
    clientID: "gfts-bearer"
    clientSecret: "${OAUTH2_PROXY_CLIENT_SECRET}"
  redis:
    enabled: true
  sessionStorage:
    type: redis
  extraArgs:
    provider: keycloak-oidc
    oidc-issuer-url: "https://iam.ivv.desp.space/realms/desp"
    whitelist-domain: gfts.developmentseed.org
    scope: openid
    insecure-oidc-allow-unverified-email: true
    email-domain: "*"
    oidc-email-claim: "sub"
    oidc-audience-claim: "azp"
    show-debug-on-error: true

ingress:
  enabled: true
  namespace: webapp
  installController: true
  className: webapp-nginx
  annotations:
    cert-manager.io/issuer: letsencrypt-webapp
    nginx.ingress.kubernetes.io/auth-signin: "https://gfts.developmentseed.org/oauth2/start"
    nginx.ingress.kubernetes.io/auth-url: "https://gfts.developmentseed.org/oauth2/auth"
  hosts:
    - host: gfts.developmentseed.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - enabled: true
      hosts:
        - gfts.developmentseed.org
      secretName: tls-webapp
      certManager: true
      certManagerIssuer: letsencrypt-webapp
      certManagerEmail: info@developmentseed.org

ingress-nginx:
  controller:
    ingressClass: webapp-nginx
    ingressClassResource:
      name: webapp-nginx
      enabled: true
      default: false
      controllerValue: "k8s.io/webapp-ingress-nginx"
    service:
      loadBalancerIP: "91.134.65.21"
      annotations:
        loadbalancer.openstack.org/floating-network-id: "Ext-Net"
        loadbalancer.ovhcloud.com/class: "octavia"
        loadbalancer.openstack.org/keep-floatingip: "true"
      externalTrafficPolicy: Local
  fullnameOverride: webapp-ingress-nginx

livenessProbe:
  httpGet:
    path: /
    port: 9000

readinessProbe:
  httpGet:
    path: /
    port: 9000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
